name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format with yapf
      run: |
        python -m pip install yapf
        yapf -vv -ri defector

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 defector
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
